### ISSUE TITLE
No license specified

### ISSUE THREAD

**Issue by indisoluble** [ogra1/ntpcontrol#1]
Hi @ogra1,

I am part of a team that is developing a product based on Ubuntu Core for our company and we would like to use this snap but, given there is no license, this software is *technically* proprietary.

Would it be possible to put this software under a license? Apache2 or MIT would be perfect but that is really your choice, of course.

Regards.

**Comment by ogra1** [comment]
fixed in 
https://github.com/ogra1/ntpcontrol/commit/be16c59cc24d473f22baa89f534f993d553aa6aa
